
/*
2016-04-16 - Incomplete First Draft of People Database


gsdeveloper3000@gmail.com
*/

CREATE DATABASE people;

DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS ASSOCIATION;
DROP TABLE IF EXISTS ASSOCIATIONS;
DROP TABLE IF EXISTS ORGANIZATION;
DROP TABLE IF EXISTS DIVISION;
DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS EMPLOYMENT_STATUSES;


CREATE TABLE PERSON
(
    PERSON_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    LASTNAME VARCHAR(25) NOT NULL,
    FIRSTNAME VARCHAR(25),
    MIDDLENAME VARCHAR(25),
    PRIMARY KEY (PERSON_ID)
);

CREATE TABLE ASSOCIATION
(
    ASSOCIATION_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    PERSON_ID INTEGER NOT NULL,
    ASSOCIATIONS_ID INTEGER NOT NULL,
    PRIMARY KEY (ASSOCIATION_ID)
);

CREATE TABLE ASSOCIATIONS
(
    ASSOCIATIONS_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    DESCRIPTION VARCHAR(25) NOT NULL,
    PRIMARY KEY (ASSOCIATION_ID)
);

CREATE TABLE ORGANIZATION
(
    ORGANIZATION_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    ORGANIZATION_NAME VARCHAR(25) NOT NULL,
    PRIMARY KEY (ORGANIZATION_ID)
);

CREATE TABLE DIVISION
(
    DIVISION_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    ORGANIZATION_ID INTEGER NOT NULL,
    DIVISION_NAME VARCHAR(25) NOT NULL,
    PRIMARY KEY (DIVISION_ID)
);

CREATE TABLE DEPARTMENT
(
    DEPARTMENT_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    DIVISION_ID INTEGER NOT NULL,
    DEPARTMENT_NAME VARCHAR(25) NOT NULL,
    PRIMARY KEY (DEPARTMENT_ID)
);

CREATE TABLE EMPLOYEE
(
    EMPLOYEE_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    PERSON_ID INTEGER NOT NULL,
    FULL_PART_STATUS VARCHAR(2) NOT NULL DEFAULT 'FT',
    TEMPORARY BOOLEAN NOT NULL DEFAULT 0,
    HIGHLY_COMPENSATED BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE PERSON_TELEPHONE
(
    TELEPHONE_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    PERSON_ID INTEGER NOT NULL,
    TELEPHONE_DESCRIPTION_ID INTEGER,
    TELEPHONE VARCHAR(25) NOT NULL,
    PRIMARY KEY (TELEPHONE_ID)
);

CREATE TABLE TELEPHONE_DESCRIPTION
(
    TELEPHONE_DESCRIPTION_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    DESCRIPTION VARCHAR(25) NOT NULL,
    PRIMARY KEY (TELEPHONE_DESCRIPTION_ID)
);

CREATE TABLE PERSON_INTERNET_ADDRESS
(
    PERSON_INTERNET_ADDRESS_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    PERSON_ID INTEGER NOT NULL,
    INTERNET_ADDRESS_DESCRIPTION_ID INTEGER,
    INTERNET_ADDRESS VARCHAR(50) NOT NULL,
    PRIMARY KEY (PERSON_INTERNET_ADDRESS_ID)
);

CREATE TABLE INTERNET_ADDRESS_DESCRIPTION
(
    INTERNET_ADDRESS_DESCRIPTION_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    DESCRIPTION VARCHAR(25) NOT NULL,
    PRIMARY KEY (INTERNET_ADDRESS_DESCRIPTION_ID)
);



/*************************************************************
**************************************************************
ASSOCIATIONS
------------
employee
consultant
customer
volunteer

TELEPHONE_DESCRIPTION
---------------------
work
home
cell

INTERNET_ADDRESS_DESCRIPTION
----------------------------
e-mail (work, home, etc. also?)
blog
homepage
facebook
LinkedIn
profile


**************************************************************
*************************************************************/

