
/*

2016-04-16 - Incomplete First Draft of People Database
2016-05-05 - Incomplete Second Draft of the People Database, not all constraints implemented
2016-06-07 - Incomplete Third Draft of the People Database

*/

CREATE DATABASE people;

USE DATABASE people;

DROP TABLE IF EXISTS PERSON
DROP TABLE IF EXISTS CONSULTANT
DROP TABLE IF EXISTS EMPLOYEE
DROP TABLE IF EXISTS MANAGER
DROP TABLE IF EXISTS EXECUTIVE
DROP TABLE IF EXISTS ORGANIZATION
DROP TABLE IF EXISTS DIVISION
DROP TABLE IF EXISTS DEPARTMENT
DROP TABLE IF EXISTS PERSON_TELEPHONE
DROP TABLE IF EXISTS DEPARTMENT_TELEPHONE
DROP TABLE IF EXISTS TELEPHONE_DESCRIPTION
DROP TABLE IF EXISTS PERSON_EMAIL_ADDRESS
DROP TABLE IF EXISTS DEPARTMENT_EMAIL_ADDRESS
DROP TABLE IF EXISTS EMAIL_ADDRESS_DESCRIPTION
DROP TABLE IF EXISTS APPLICANT
DROP TABLE IF EXISTS CUSTOMER
DROP TABLE IF EXISTS FORMER_CUSTOMER
DROP TABLE IF EXISTS CONTRACTOR


CREATE TABLE PERSON
(
    PERSON_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    LASTNAME VARCHAR(25) NOT NULL,
    FIRSTNAME VARCHAR(25),
    MIDDLENAME VARCHAR(25),
    BIRTHDAY DATE,
    CONSULTANT_ID INTEGER,
    CONTRACTOR_ID INTEGER,
    EMPLOYEE_ID INTEGER,
    EXECUTIVE_ID INTEGER,
    MANAGER_ID INTEGER,
    APPLICANT_ID INTEGER,
    CUSTOMER_ID INTEGER,
    FORMER_CUSTOMER_ID INTEGER,
    PRIMARY KEY (PERSON_ID)
);

CREATE TABLE CONSULTANT
(
    CONSULTANT_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER,
    FULL_PART_STATUS VARCHAR(2) NOT NULL DEFAULT 'FT',
    TEMPORARY BOOLEAN NOT NULL DEFAULT 0,
    HIGHLY_COMPENSATED BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (CONSULTANT_ID)
);

CREATE TABLE CONTRACTOR
(
    CONTRACTOR_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER,
    FULL_PART_STATUS VARCHAR(2) NOT NULL DEFAULT 'FT',
    TEMPORARY BOOLEAN NOT NULL DEFAULT 0,
    HIGHLY_COMPENSATED BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (CONTRACTOR_ID)
);

CREATE TABLE EMPLOYEE
(
    EMPLOYEE_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    FULL_PART_STATUS VARCHAR(2) NOT NULL DEFAULT 'FT',
    TEMPORARY BOOLEAN NOT NULL DEFAULT 0,
    HIGHLY_COMPENSATED BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE MANAGER
(
    MANAGER_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    FULL_PART_STATUS VARCHAR(2) NOT NULL DEFAULT 'FT',
    TEMPORARY BOOLEAN NOT NULL DEFAULT 0,
    HIGHLY_COMPENSATED BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (MANAGER_ID)
);

CREATE TABLE EXECUTIVE
(
    EXECUTIVE_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    FULL_PART_STATUS VARCHAR(2) NOT NULL DEFAULT 'FT',
    TEMPORARY BOOLEAN NOT NULL DEFAULT 0,
    HIGHLY_COMPENSATED BOOLEAN NOT NULL DEFAULT 1,
    PRIMARY KEY (EXECUTIVE_ID)
);

/* A one row table to properly define structure. */
CREATE TABLE ORGANIZATION
(
    ORGANIZATION_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER,
    ORGANIZATION_NAME VARCHAR(25) NOT NULL,
    PRIMARY KEY (ORGANIZATION_ID)
);

CREATE TABLE DIVISION
(
    DIVISION_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER,
    ORGANIZATION_ID INTEGER NOT NULL,
    DIVISION_NAME VARCHAR(25) NOT NULL,
    PRIMARY KEY (DIVISION_ID)
);

ALTER TABLE DIVISION ADD CONSTRAINT division_organization_id_fk 
            FOREIGN KEY (ORGANIZATION_ID)
            REFERENCES PERSON(ORGANIZATION_ID);

CREATE TABLE DEPARTMENT
(
    DEPARTMENT_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    DIVISION_ID INTEGER NOT NULL,
    DEPARTMENT_NAME VARCHAR(25) NOT NULL,
    PRIMARY KEY (DEPARTMENT_ID)
);

ALTER TABLE DEPARTMENT ADD CONSTRAINT department_division_id_fk 
            FOREIGN KEY (DIVISION_ID)
            REFERENCES PERSON(DIVISION_ID);

CREATE TABLE PERSON_TELEPHONE
(
    PERSON_TELEPHONE_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    PERSON_ID INTEGER NOT NULL,
    TELEPHONE_DESCRIPTION_ID INTEGER,
    PERSON_TELEPHONE VARCHAR(25) NOT NULL,
    PRIMARY KEY (PERSON_TELEPHONE_ID)
);

ALTER TABLE PERSON_TELEPHONE ADD CONSTRAINT person_telephone_person_id_fk
            FOREIGN KEY (PERSON_ID)
            REFERENCES PERSON(PERSON_ID);

CREATE TABLE DEPARTMENT_TELEPHONE
(
    DEPARTMENT_TELEPHONE_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    DEPARTMENT_ID INTEGER NOT NULL,
    TELEPHONE_DESCRIPTION_ID INTEGER,
    DEPARTMENT_TELEPHONE VARCHAR(25) NOT NULL,
    PRIMARY KEY (DEPARTMENT_TELEPHONE_ID)
);

--ALTER TABLE ...

CREATE TABLE TELEPHONE_DESCRIPTION
(
    TELEPHONE_DESCRIPTION_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    DESCRIPTION VARCHAR(25) NOT NULL,
    PRIMARY KEY (TELEPHONE_DESCRIPTION_ID)
);

CREATE TABLE PERSON_EMAIL_ADDRESS
(
    PERSON_EMAIL_ADDRESS_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    PERSON_ID INTEGER NOT NULL,
    EMAIL_ADDRESS_DESCRIPTION_ID INTEGER,
    PERSON_EMAIL_ADDRESS VARCHAR(50) NOT NULL,
    PRIMARY KEY (PERSON_EMAIL_ADDRESS_ID)
);

CREATE TABLE DEPARTMENT_EMAIL_ADDRESS
(
    DEPARTMENT_EMAIL_ADDRESS_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    DEPARTMENT_ID INTEGER NOT NULL,
    EMAIL_ADDRESS_DESCRIPTION_ID INTEGER,
    DEPARTMENT_EMAIL_ADDRESS VARCHAR(50) NOT NULL,
    PRIMARY KEY (DEPARTMENT_EMAIL_ADDRESS_ID)
);

CREATE TABLE EMAIL_ADDRESS_DESCRIPTION
(
    EMAIL_ADDRESS_DESCRIPTION_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    DESCRIPTION VARCHAR(25) NOT NULL,
    PRIMARY KEY (EMAIL_ADDRESS_DESCRIPTION_ID)
);

CREATE TABLE APPLICANT
(
    APPLICANT_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER,
    APPLICATION_DATE DATE,
    PRIMARY KEY (APPLICANT_ID)
);

CREATE TABLE CUSTOMER
(
    CUSTOMER_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER,
    DATE_OF_PURCHASE DATE,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE FORMER_CUSTOMER
(
    FORMER_CUSTOMER_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER,
    EFFECTIVE_DATE DATE,
    PRIMARY KEY (FORMER_CUSTOMER_ID)
);

