
/*

2016-04-16 - Incomplete First Draft of People Database
2016-05-05 - Incomplete Second Draft of the People Database, not all constraints implemented
2016-06-07 - Incomplete Third Draft of the People Database
2016-06-22 - Added USER_TABLE table to this Fourth People Database Draft
2016-07-08 - Added AddressBook Tables

*/

CREATE DATABASE people;

USE DATABASE people;

DROP TABLE IF EXISTS PERSON
DROP TABLE IF EXISTS PERSONAL_RELATIONSHIP
DROP TABLE IF EXISTS CONSULTANT
DROP TABLE IF EXISTS CONTRACTOR
DROP TABLE IF EXISTS EMPLOYEE
DROP TABLE IF EXISTS MANAGER
DROP TABLE IF EXISTS EXECUTIVE
DROP TABLE IF EXISTS TITLE
DROP TABLE IF EXISTS USER_TABLE
DROP TABLE IF EXISTS ORGANIZATION
DROP TABLE IF EXISTS DIVISION
DROP TABLE IF EXISTS DEPARTMENT
DROP TABLE IF EXISTS PERSON_ADDRESS
DROP TABLE IF EXISTS PERSON_ADDRESS_DESCRIPTION
DROP TABLE IF EXISTS PERSON_TELEPHONE
DROP TABLE IF EXISTS PERSON_TELEPHONE_DESCRIPTION
DROP TABLE IF EXISTS DEPARTMENT_TELEPHONE
DROP TABLE IF EXISTS ORGANIZATION_TELEPHONE
DROP TABLE IF EXISTS DEPARTMENT_TELEPHONE_DESCRIPTION
DROP TABLE IF EXISTS ORGANIZATION_TELEPHONE_DESCRIPTION
DROP TABLE IF EXISTS PERSON_EMAIL_ADDRESS
DROP TABLE IF EXISTS DEPARTMENT_EMAIL_ADDRESS
DROP TABLE IF EXISTS EMAIL_ADDRESS_DESCRIPTION
DROP TABLE IF EXISTS ORGANIZATION_ADDRESS
DROP TABLE IF EXISTS ORGANIZATION_ADDRESS_DESCRIPTION
DROP TABLE IF EXISTS APPLICANT
DROP TABLE IF EXISTS CUSTOMER
DROP TABLE IF EXISTS FORMER_CUSTOMER

CREATE TABLE PERSON
(
    PERSON_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    LASTNAME VARCHAR(25) NOT NULL,
    FIRSTNAME VARCHAR(25),
    MIDDLENAME VARCHAR(25),
    BIRTHDAY DATE,
    CONSULTANT_ID INTEGER,
    CONTRACTOR_ID INTEGER,
    EMPLOYEE_ID INTEGER,
    EXECUTIVE_ID INTEGER,
    MANAGER_ID INTEGER,
    APPLICANT_ID INTEGER,
    CUSTOMER_ID INTEGER,
    FORMER_CUSTOMER_ID INTEGER,
    PRIMARY KEY (PERSON_ID)
);

CREATE TABLE PERSONAL_RELATIONSHIP
(
	RELATIONSHIP VARCHAR(20)  NOT NULL UNIQUE
);

INSERT INTO PERSONAL_RELATIONSHIP (RELATIONSHIP) VALUES ('Associate');
INSERT INTO PERSONAL_RELATIONSHIP (RELATIONSHIP) VALUES ('Business');
INSERT INTO PERSONAL_RELATIONSHIP (RELATIONSHIP) VALUES ('Other');
INSERT INTO PERSONAL_RELATIONSHIP (RELATIONSHIP) VALUES ('Personal');
INSERT INTO PERSONAL_RELATIONSHIP (RELATIONSHIP) VALUES ('Professional');
INSERT INTO PERSONAL_RELATIONSHIP (RELATIONSHIP) VALUES ('Relative');
INSERT INTO PERSONAL_RELATIONSHIP (RELATIONSHIP) VALUES ('Unsolicited');


CREATE TABLE CONSULTANT
(
    CONSULTANT_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER,
    FULL_PART_STATUS VARCHAR(2) NOT NULL DEFAULT 'FT',
    TEMPORARY BOOLEAN NOT NULL DEFAULT 0,
    HIGHLY_COMPENSATED BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (CONSULTANT_ID)
);

CREATE TABLE CONTRACTOR
(
    CONTRACTOR_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER,
    FULL_PART_STATUS VARCHAR(2) NOT NULL DEFAULT 'FT',
    TEMPORARY BOOLEAN NOT NULL DEFAULT 0,
    HIGHLY_COMPENSATED BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (CONTRACTOR_ID)
);

CREATE TABLE EMPLOYEE
(
    EMPLOYEE_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    FULL_PART_STATUS VARCHAR(2) NOT NULL DEFAULT 'FT',
    TEMPORARY BOOLEAN NOT NULL DEFAULT 0,
    HIGHLY_COMPENSATED BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE MANAGER
(
    MANAGER_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    FULL_PART_STATUS VARCHAR(2) NOT NULL DEFAULT 'FT',
    TEMPORARY BOOLEAN NOT NULL DEFAULT 0,
    HIGHLY_COMPENSATED BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (MANAGER_ID)
);

CREATE TABLE EXECUTIVE
(
    EXECUTIVE_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    FULL_PART_STATUS VARCHAR(2) NOT NULL DEFAULT 'FT',
    TEMPORARY BOOLEAN NOT NULL DEFAULT 0,
    HIGHLY_COMPENSATED BOOLEAN NOT NULL DEFAULT 1,
    PRIMARY KEY (EXECUTIVE_ID)
);

CREATE TABLE TITLE
(
    TITLE_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER,
    TITLE VARCHAR(30)  NOT NULL UNIQUE,
    PRIMARY KEY (TITLE_ID)
);

CREATE TABLE USER_TABLE
(
    USER_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    PERSON_ID INTEGER,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE ORGANIZATION
(
    ORGANIZATION_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER,
    ORGANIZATION_NAME VARCHAR(25) NOT NULL,
    PRIMARY KEY (ORGANIZATION_ID)
);

CREATE TABLE DIVISION
(
    DIVISION_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER,
    ORGANIZATION_ID INTEGER NOT NULL,
    DIVISION_NAME VARCHAR(25) NOT NULL,
    PRIMARY KEY (DIVISION_ID)
);

ALTER TABLE DIVISION ADD CONSTRAINT division_organization_id_fk 
            FOREIGN KEY (ORGANIZATION_ID)
            REFERENCES PERSON(ORGANIZATION_ID);

CREATE TABLE DEPARTMENT
(
    DEPARTMENT_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    DIVISION_ID INTEGER NOT NULL,
    DEPARTMENT_NAME VARCHAR(25) NOT NULL,
    PRIMARY KEY (DEPARTMENT_ID)
);

ALTER TABLE DEPARTMENT ADD CONSTRAINT department_division_id_fk 
            FOREIGN KEY (DIVISION_ID)
            REFERENCES PERSON(DIVISION_ID);

CREATE TABLE PERSON_ADDRESS
(
    ADDRESS_ID INTEGER	NOT NULL AUTO_INCREMENT,
    PERSON_ID INTEGER	NOT NULL,
    PERSON_ADDRESS_DESCRIPTION_ID INTEGER,
    ADDRESS_LINE_1 VARCHAR(50)	NOT NULL,
    ADDRESS_LINE_2 VARCHAR(50),
    ADDRESS_LINE_3 VARCHAR(50),
    ADDRESS_LINE_4 VARCHAR(50),
    CITY VARCHAR(50)	NOT NULL,
    STATE VARCHAR(50)	NOT NULL,
    POSTAL_CODE VARCHAR(15)		NOT NULL,
    COUNTRY VARCHAR(50)			NOT NULL,
    PRIMARY KEY (ADDRESS_ID)
);

ALTER TABLE PERSON_ADDRESS ADD CONSTRAINT person_address_person_id_fk 
            FOREIGN KEY (PERSON_ID)
            REFERENCES PERSON(PERSON_ID);

CREATE TABLE PERSON_ADDRESS_DESCRIPTION
(
    PERSON_ADDRESS_DESCRIPTION_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    DESCRIPTION VARCHAR(30)  NOT NULL UNIQUE,
    PRIMARY KEY (PERSON_ADDRESS_DESCRIPTION_ID)
);

INSERT INTO PERSON_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Home');
INSERT INTO PERSON_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Office');
INSERT INTO PERSON_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Vacation');

CREATE TABLE PERSON_TELEPHONE
(
    PERSON_TELEPHONE_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    PERSON_ID INTEGER NOT NULL,
    TELEPHONE_DESCRIPTION_ID INTEGER,
    PERSON_TELEPHONE VARCHAR(25) NOT NULL,
    PRIMARY KEY (PERSON_TELEPHONE_ID)
);

ALTER TABLE PERSON_TELEPHONE ADD CONSTRAINT person_telephone_person_id_fk
            FOREIGN KEY (PERSON_ID)
            REFERENCES PERSON(PERSON_ID);

CREATE TABLE DEPARTMENT_TELEPHONE
(
    DEPARTMENT_TELEPHONE_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    DEPARTMENT_ID INTEGER NOT NULL,
    TELEPHONE_DESCRIPTION_ID INTEGER,
    DEPARTMENT_TELEPHONE VARCHAR(25) NOT NULL,
    PRIMARY KEY (DEPARTMENT_TELEPHONE_ID)
);

--ALTER TABLE ...

CREATE TABLE ORGANIZATION_TELEPHONE
(
    ORGANIZATION_TELEPHONE_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    ORGANIZATION_ID INTEGER NOT NULL,
    ORGANIZATION_TELEPHONE_DESCRIPTION_ID INTEGER,
    DEPARTMENT_TELEPHONE VARCHAR(25) NOT NULL,
    PRIMARY KEY (ORGANIZATION_TELEPHONE_ID)
);

CREATE TABLE PERSON_TELEPHONE_DESCRIPTION
(
    PERSON_TELEPHONE_DESCRIPTION_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    DESCRIPTION VARCHAR(25) NOT NULL,
    PRIMARY KEY (PERSON_TELEPHONE_DESCRIPTION_ID)
);

INSERT INTO PERSON_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Cell');
INSERT INTO PERSON_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Fax');
INSERT INTO PERSON_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Home');
INSERT INTO PERSON_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Office');
INSERT INTO PERSON_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Other');

CREATE TABLE ORGANIZATION_TELEPHONE_DESCRIPTION
(
    ORGANIZATION_TELEPHONE_DESCRIPTION_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    DESCRIPTION VARCHAR(25) NOT NULL,
    PRIMARY KEY (ORGANIZATION_TELEPHONE_DESCRIPTION_ID)
);

INSERT INTO ORGANIZATION_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Cell');
INSERT INTO ORGANIZATION_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Fax');
INSERT INTO ORGANIZATION_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Home');
INSERT INTO ORGANIZATION_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Office');
INSERT INTO ORGANIZATION_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Other');

CREATE TABLE DEPARTMENT_TELEPHONE_DESCRIPTION
(
    DEPARTMENT_TELEPHONE_DESCRIPTION_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    DESCRIPTION VARCHAR(25) NOT NULL,
    PRIMARY KEY (DEPARTMENT_TELEPHONE_DESCRIPTION_ID)
);

INSERT INTO DEPARTMENT_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Cell');
INSERT INTO DEPARTMENT_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Fax');
INSERT INTO DEPARTMENT_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Home');
INSERT INTO DEPARTMENT_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Office');
INSERT INTO DEPARTMENT_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Other');


CREATE TABLE PERSON_EMAIL_ADDRESS
(
    PERSON_EMAIL_ADDRESS_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    PERSON_ID INTEGER NOT NULL,
    EMAIL_ADDRESS_DESCRIPTION_ID INTEGER,
    PERSON_EMAIL_ADDRESS VARCHAR(50) NOT NULL,
    PRIMARY KEY (PERSON_EMAIL_ADDRESS_ID)
);

CREATE TABLE DEPARTMENT_EMAIL_ADDRESS
(
    DEPARTMENT_EMAIL_ADDRESS_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    DEPARTMENT_ID INTEGER NOT NULL,
    EMAIL_ADDRESS_DESCRIPTION_ID INTEGER,
    DEPARTMENT_EMAIL_ADDRESS VARCHAR(50) NOT NULL,
    PRIMARY KEY (DEPARTMENT_EMAIL_ADDRESS_ID)
);

CREATE TABLE EMAIL_ADDRESS_DESCRIPTION
(
    EMAIL_ADDRESS_DESCRIPTION_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    DESCRIPTION VARCHAR(25) NOT NULL,
    PRIMARY KEY (EMAIL_ADDRESS_DESCRIPTION_ID)
);

INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Cell');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Office');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Other');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Personal');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Professional');

CREATE TABLE ORGANIZATION_ADDRESS
(
    ADDRESS_ID INTEGER	NOT NULL AUTO_INCREMENT,
    ORGANIZATION_ID INTEGER	NOT NULL,
    ORGANIZATION_ADDRESS_DESCRIPTION_ID INTEGER,
    ADDRESS_LINE_1 VARCHAR(50)	NOT NULL,
    ADDRESS_LINE_2 VARCHAR(50),
    ADDRESS_LINE_3 VARCHAR(50),
    ADDRESS_LINE_4 VARCHAR(50),
    CITY VARCHAR(50)	NOT NULL,
    STATE VARCHAR(50)	NOT NULL,
    POSTAL_CODE VARCHAR(15)		NOT NULL,
    COUNTRY VARCHAR(50)			NOT NULL,
    PRIMARY KEY (ADDRESS_ID)
);

ALTER TABLE ORGANIZATION_ADDRESS ADD CONSTRAINT organization_address_organization_id_fk 
            FOREIGN KEY (ORGANIZATION_ID)
            REFERENCES PERSON(ORGANIZATION_ID);

CREATE TABLE ORGANIZATION_ADDRESS_DESCRIPTION
(
    ORGANIZATION_ADDRESS_DESCRIPTION_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER, 
    DESCRIPTION VARCHAR(20)  NOT NULL UNIQUE,
    PRIMARY KEY (PERSON_ADDRESS_DESCRIPTION_ID)
);

INSERT INTO ORGANIZATION_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Headquarters');
INSERT INTO ORGANIZATION_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Subsidiary');
INSERT INTO ORGANIZATION_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Field Office');

CREATE TABLE APPLICANT
(
    APPLICANT_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER,
    APPLICATION_DATE DATE,
    PRIMARY KEY (APPLICANT_ID)
);

CREATE TABLE CUSTOMER
(
    CUSTOMER_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER,
    DATE_OF_PURCHASE DATE,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE FORMER_CUSTOMER
(
    FORMER_CUSTOMER_ID INTEGER NOT NULL AUTO_INCREMENT,
    VERSION INTEGER,
    EFFECTIVE_DATE DATE,
    PRIMARY KEY (FORMER_CUSTOMER_ID)
);

