
/*

2016-04-16 - Incomplete First Draft of People Database
2016-05-05 - Incomplete Second Draft of the People Database, not all constraints implemented
2016-06-07 - Incomplete Third Draft of the People Database
2016-06-22 - Added USER_TABLE table to this Fourth People Database Draft
2016-07-08 - Added AddressBook Tables
2017-01-18 - Converted to Oracle DB and added/modified several tables
*/


SET ECHO OFF 


DROP USER CENTRAL CASCADE;

CREATE USER CENTRAL IDENTIFIED BY central;

GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO CENTRAL;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, CREATE PROCEDURE, RESOURCE TO CENTRAL;

CONNECT CENTRAL/central;


--left over from mysql script, left for documentation (all objects dropped above). will remove later.
DROP TABLE PERSON
DROP TABLE PERSONAL_RELATIONSHIP
DROP TABLE CONSULTANT
DROP TABLE CONTRACTOR
DROP TABLE EMPLOYEE
DROP TABLE MANAGER
DROP TABLE MEMBER
DROP TABLE EXECUTIVE
DROP TABLE TITLE
DROP TABLE USER_TABLE
DROP TABLE BUSINESS
DROP TABLE DIVISION
DROP TABLE DEPARTMENT
DROP TABLE PERSON_ADDRESS
DROP TABLE PERSON_ADDRESS_DESCRIPTION
DROP TABLE PERSON_TELEPHONE
DROP TABLE PERSON_TELEPHONE_DESCRIPTION
DROP TABLE DEPARTMENT_TELEPHONE
DROP TABLE BUSINESS_TELEPHONE
DROP TABLE DEPARTMENT_TELEPHONE_DESCRIPTION
DROP TABLE BUSINESS_TELEPHONE_DESCRIPTION
DROP TABLE PERSON_EMAIL_ADDRESS
DROP TABLE DEPARTMENT_EMAIL_ADDRESS
DROP TABLE EMAIL_ADDRESS_DESCRIPTION
DROP TABLE BUSINESS_ADDRESS
DROP TABLE BUSINESS_ADDRESS_DESCRIPTION

DROP TABLE UNION_TABLE
DROP TABLE UNION_ADDRESS
DROP TABLE UNION_TELEPHONE
DROP TABLE UNION_EMAIL
DROP TABLE UNION_WEBSITE

DROP TABLE UNION_LOCAL
DROP TABLE UNION_LOCAL_ADDRESS
DROP TABLE UNION_LOCAL_TELEPHONE
DROP TABLE UNION_LOCAL_EMAIL
DROP TABLE UNION_LOCAL_WEBSITE



CREATE TABLE CONSULTANT
(
    CONSULTANT_ID NUMBER,
    VERSION NUMBER,
	PERSON_ID NUMBER,
    FULL_PART_STATUS CHAR(2) DEFAULT 'FT' CONSTRAINT consul_full_part_nn NOT NULL,
    TEMPORARY_STATUS CHAR(1) DEFAULT 'Y' CONSTRAINT consul_temp_status_nn NOT NULL,
    HIGHLY_COMPENSATED CHAR(1) DEFAULT 'Y' CONSTRAINT consul_highly_comp_nn NOT NULL,
    PRIMARY KEY (CONSULTANT_ID)
);

CREATE TABLE CONTRACTOR
(
    CONTRACTOR_ID NUMBER,
    VERSION NUMBER,
	PERSON_ID NUMBER,
    FULL_PART_STATUS CHAR(2) DEFAULT 'FT' CONSTRAINT contract_full_part_nn NOT NULL,
    END_DATE DATE CONSTRAINT contract_end_date_nn NOT NULL,
    HIGHLY_COMPENSATED CHAR(1) DEFAULT 'Y' CONSTRAINT contract_highly_comp_nn NOT NULL,
    PRIMARY KEY (CONTRACTOR_ID)
);

CREATE TABLE EMPLOYEE
(
    EMPLOYEE_ID NUMBER,
    VERSION NUMBER,
	PERSON_ID NUMBER,
    FULL_PART_STATUS CHAR(2) DEFAULT 'FT' CONSTRAINT emp_full_part_nn NOT NULL,
    TEMPORARY_STATUS CHAR(1) DEFAULT 'Y' CONSTRAINT emp_temp_status_nn NOT NULL,
    HIGHLY_COMPENSATED CHAR(1) DEFAULT 'Y' CONSTRAINT emp_highly_comp_nn NOT NULL,
    PRIMARY KEY (EMPLOYEE_ID)
);

ALTER TABLE EMPLOYEE ADD 
( 
	CONSTRAINT emp_full_part_chk
		 CHECK (FULL_PART_STATUS in ('FT', 'PT')),
	CONSTRAINT emp_temp_status_chk 
		CHECK (TEMPORARY_STATUS in ('Y', 'N')),
	CONSTRAINT emp_highly_comp_chk 
		CHECK (HIGHLY_COMPENSATED in ('Y', 'N'))
) ;


CREATE TABLE EXECUTIVE
(
    EXECUTIVE_ID NUMBER,
    VERSION NUMBER, 
	PERSON_ID NUMBER,
    FULL_PART_STATUS CHAR(2) DEFAULT 'FT' CONSTRAINT exec_full_part_nn NOT NULL,
    TEMPORARY_STATUS CHAR(1) DEFAULT 'Y' CONSTRAINT exec_temp_status_nn NOT NULL,
    HIGHLY_COMPENSATED CHAR(1) DEFAULT 'Y' CONSTRAINT exec_highly_comp_nn NOT NULL,
    PRIMARY KEY (EXECUTIVE_ID)
);

CREATE TABLE MANAGER
(
    MANAGER_ID NUMBER,
    VERSION NUMBER, 
	PERSON_ID NUMBER,
    FULL_PART_STATUS CHAR(2) DEFAULT 'FT' CONSTRAINT man_full_part_nn NOT NULL,
    TEMPORARY_STATUS CHAR(1) DEFAULT 'Y' CONSTRAINT man_temp_status_nn NOT NULL,
    HIGHLY_COMPENSATED CHAR(1) DEFAULT 'Y' CONSTRAINT man_highly_comp_nn NOT NULL,
    PRIMARY KEY (MANAGER_ID)
);

CREATE TABLE MEMBER
(
    MEMBER_ID NUMBER CONSTRAINT member_id_nn NOT NULL,
    VERSION NUMBER, 
	PERSON_ID NUMBER,
    FULL_PART_STATUS VARCHAR2(2) CONSTRAINT FULL_PART_STATUS_nn NOT NULL, DEFAULT 'FT',
    TEMPORARY_STATUS BOOLEAN CONSTRAINT TEMPORARY_STATUS_nn NOT NULL DEFAULT 0,
    HIGHLY_COMPENSATED BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (MEMBER_ID)
);


CREATE TABLE PERSON
(
    PERSON_ID NUMBER,
    VERSION NUMBER, 
    LASTNAME VARCHAR2(25) CONSTRAINT lastname_nn NOT NULL,
    FIRSTNAME VARCHAR2(25),
    MIDDLENAME VARCHAR2(25),
    BIRTHDAY DATE,
    PRIMARY KEY (PERSON_ID)
);

ALTER TABLE PERSON ADD 
(
	CONSTRAINT person_relation_fk
		FOREIGN KEY (PERSONAL_RELATIONSHIP_ID)
		REFERENCES PERSONAL_RELATIONSHIP(PERSONAL_RELATIONSHIP_ID),
	CONSTRAINT person_consultant_fk
		FOREIGN KEY (CONSULTANT_ID)
		REFERENCES CONSULTANT(CONSULTANT_ID),
	CONSTRAINT person_contractor_fk
		FOREIGN KEY (CONTRACTOR_ID)
		REFERENCES CONTRACTOR(CONTRACTOR_ID),
	CONSTRAINT person_employee_fk
		FOREIGN KEY (EMPLOYEE_ID)
		REFERENCES EMPLOYEE(EMPLOYEE_ID),
	CONSTRAINT person_executive_fk
		FOREIGN KEY (EXECUTIVE_ID)
		REFERENCES EXECUTIVE(EXECUTIVE_ID),
	CONSTRAINT person_manager_fk
		FOREIGN KEY (MANAGER_ID)
		REFERENCES MANAGER(MANAGER_ID),
	CONSTRAINT person_applicant_fk
		FOREIGN KEY (APPLICANT_ID)
		REFERENCES APPLICANT(APPLICANT_ID)
);

CREATE TABLE PERSONAL_RELATIONSHIP
(
    PERSONAL_RELATIONSHIP_ID NUMBER,
    VERSION NUMBER, 
    RELATIONSHIP VARCHAR2(25) CONSTRAINT relationship_nn NOT NULL UNIQUE,
    PRIMARY KEY (PERSONAL_RELATIONSHIP_ID)
);

INSERT INTO PERSONAL_RELATIONSHIP (RELATIONSHIP) VALUES ('Associate');
INSERT INTO PERSONAL_RELATIONSHIP (RELATIONSHIP) VALUES ('Business');
INSERT INTO PERSONAL_RELATIONSHIP (RELATIONSHIP) VALUES ('Other');
INSERT INTO PERSONAL_RELATIONSHIP (RELATIONSHIP) VALUES ('Personal');
INSERT INTO PERSONAL_RELATIONSHIP (RELATIONSHIP) VALUES ('Professional');
INSERT INTO PERSONAL_RELATIONSHIP (RELATIONSHIP) VALUES ('Relative');
INSERT INTO PERSONAL_RELATIONSHIP (RELATIONSHIP) VALUES ('Unsolicited');

CREATE TABLE PERSON_ADDRESS
(
    ADDRESS_ID NUMBER,
    PERSON_ID NUMBER CONSTRAINT person_id_nn NOT NULL,
    PERSON_ADDRESS_DESCRIPTION_ID NUMBER,
    STREET VARCHAR2(50) CONSTRAINT street_nn NOT NULL,
    ADDRESS_LINE_2 VARCHAR2(50),
    CITY VARCHAR2(50) CONSTRAINT city_nn NOT NULL,
    STATE VARCHAR2(50) CONSTRAINT state_nn NOT NULL,
    POSTAL_CODE VARCHAR2(15) CONSTRAINT postal_code_nn NOT NULL,
    COUNTRY VARCHAR2(50) CONSTRAINT country_nn NOT NULL,
    PRIMARY KEY (ADDRESS_ID)
);

ALTER TABLE PERSON_ADDRESS ADD 
(
	CONSTRAINT person_address_person_id_fk
		FOREIGN KEY (ADDRESS_ID)
		REFERENCES PERSON_ADDRESS(ADDRESS_ID);
);

CREATE TABLE PERSON_ADDRESS_DESCRIPTION
(
    PERSON_ADDRESS_DESCRIPTION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(30)  NOT NULL UNIQUE,
    PRIMARY KEY (PERSON_ADDRESS_DESCRIPTION_ID)
);

INSERT INTO PERSON_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Home');
INSERT INTO PERSON_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Office');
INSERT INTO PERSON_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Vacation');

CREATE TABLE PERSON_TELEPHONE
(
    PERSON_TELEPHONE_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    PERSON_ID NUMBER NOT NULL,
    TELEPHONE_DESCRIPTION_ID NUMBER,
    PERSON_TELEPHONE VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (PERSON_TELEPHONE_ID)
);

ALTER TABLE PERSON_TELEPHONE ADD CONSTRAINT person_telephone_person_id_fk
            FOREIGN KEY (PERSON_ID)
            REFERENCES PERSON(PERSON_ID);

CREATE TABLE PERSON_TELEPHONE_DESCRIPTION
(
    PERSON_TELEPHONE_DESCRIPTION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (PERSON_TELEPHONE_DESCRIPTION_ID)
);

INSERT INTO PERSON_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Cell');
INSERT INTO PERSON_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Fax');
INSERT INTO PERSON_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Home');
INSERT INTO PERSON_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Office');
INSERT INTO PERSON_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Other');

CREATE TABLE PERSON_EMAIL_ADDRESS
(
    PERSON_EMAIL_ADDRESS_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    PERSON_ID NUMBER NOT NULL,
    EMAIL_ADDRESS_DESCRIPTION_ID NUMBER,
    PERSON_EMAIL_ADDRESS VARCHAR2(50) CONSTRAINT  NOT NULL,
    PRIMARY KEY (PERSON_EMAIL_ADDRESS_ID)
);

CREATE TABLE PERSON_WEBSITE_ADDRESS
(
    PERSON_WEBSITE_ADDRESS_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    PERSON_ID NUMBER NOT NULL,
    WEBSITE_ADDRESS_DESCRIPTION_ID NUMBER,
    PERSON_WEBSITE_ADDRESS VARCHAR2(255) CONSTRAINT  NOT NULL,
    PRIMARY KEY (PERSON_WEBSITE_ADDRESS_ID)
);


CREATE TABLE TITLE
(
    TITLE_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER,
    TITLE VARCHAR2(30) CONSTRAINT  NOT NULL, 
	CONSTRAINT title_un UNIQUE (TITLE),
    PRIMARY KEY (TITLE_ID)
);

CREATE TABLE USER_TABLE
(
    USER_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    PERSON_ID NUMBER,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE BUSINESS
(
    BUSINESS_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER,
    BUSINESS_NAME VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (BUSINESS_ID)
);

CREATE TABLE BUSINESS_TELEPHONE
(
    BUSINESS_TELEPHONE_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    BUSINESS_ID NUMBER NOT NULL,
    BUSINESS_TELEPHONE_DESCRIPTION_ID NUMBER,
    UNION_TELEPHONE VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (BUSINESS_TELEPHONE_ID)
);

CREATE TABLE BUSINESS_TELEPHONE_DESCRIPTION
(
    BUSINESS_TELEPHONE_DESCRIPTION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (BUSINESS_TELEPHONE_DESCRIPTION_ID)
);

INSERT INTO BUSINESS_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Cell');
INSERT INTO BUSINESS_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Fax');
INSERT INTO BUSINESS_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Home');
INSERT INTO BUSINESS_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Office');
INSERT INTO BUSINESS_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Other');

CREATE TABLE BUSINESS_EMAIL_ADDRESS
(
    BUSINESS_EMAIL_ADDRESS_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    BUSINESS_ID NUMBER NOT NULL,
    EMAIL_ADDRESS_DESCRIPTION_ID NUMBER,
    BUSINESS_EMAIL_ADDRESS VARCHAR2(50) CONSTRAINT  NOT NULL,
    PRIMARY KEY (BUSINESS_EMAIL_ADDRESS_ID)
);

CREATE TABLE BUSINESS_ADDRESS
(
    ADDRESS_ID NUMBER	CONSTRAINT  NOT NULL,
    BUSINESS_ID NUMBER	NOT NULL,
    BUSINESS_ADDRESS_DESCRIPTION_ID NUMBER,
    STREET VARCHAR2(50)	NOT NULL,
    MAIL_STOP VARCHAR2(50),
    CITY VARCHAR2(50)	NOT NULL,
    STATE VARCHAR2(50)	NOT NULL,
    POSTAL_CODE VARCHAR2(15)		NOT NULL,
    COUNTRY VARCHAR2(50)			NOT NULL,
    PRIMARY KEY (ADDRESS_ID)
);

ALTER TABLE BUSINESS_ADDRESS ADD CONSTRAINT business_address_business_id_fk 
            FOREIGN KEY (BUSINESS_ID)
            REFERENCES PERSON(BUSINESS_ID);

CREATE TABLE BUSINESS_ADDRESS_DESCRIPTION
(
    BUSINESS_ADDRESS_DESCRIPTION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(20)  NOT NULL UNIQUE,
    PRIMARY KEY (PERSON_ADDRESS_DESCRIPTION_ID)
);

INSERT INTO BUSINESS_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Division');
INSERT INTO BUSINESS_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Field Office');
INSERT INTO BUSINESS_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Headquarters');
INSERT INTO BUSINESS_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Subsidiary');


CREATE TABLE BUSINESS_TELEPHONE
(
    BUSINESS_TELEPHONE_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    BUSINESS_ID NUMBER NOT NULL,
    BUSINESS_TELEPHONE_DESCRIPTION_ID NUMBER,
    DEPARTMENT_TELEPHONE VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (BUSINESS_TELEPHONE_ID)
);

CREATE TABLE BUSINESS_TELEPHONE_DESCRIPTION
(
    BUSINESS_TELEPHONE_DESCRIPTION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (BUSINESS_TELEPHONE_DESCRIPTION_ID)
);

INSERT INTO BUSINESS_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Cell');
INSERT INTO BUSINESS_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Fax');
INSERT INTO BUSINESS_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Home');
INSERT INTO BUSINESS_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Office');
INSERT INTO BUSINESS_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Other');


CREATE TABLE BUSINESS_EMAIL_ADDRESS
(
    BUSINESS_EMAIL_ADDRESS_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    BUSINESS_ID NUMBER NOT NULL,
    EMAIL_ADDRESS_DESCRIPTION_ID NUMBER,
    BUSINESS_EMAIL_ADDRESS VARCHAR2(50) CONSTRAINT  NOT NULL,
    PRIMARY KEY (BUSINESS_EMAIL_ADDRESS_ID)
);

CREATE TABLE BUSINESS_EMAIL_ADDRESS_DESCRIPTION
(
    BUSINESS_EMAIL_ADDRESS_DESCRIPTION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (BUSINESS_EMAIL_ADDRESS_DESCRIPTION_ID)
);

INSERT INTO BUSINESS_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Business');
INSERT INTO BUSINESS_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Cell');
INSERT INTO BUSINESS_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Corporate');
INSERT INTO BUSINESS_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Departmental');
INSERT INTO BUSINESS_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Office');
INSERT INTO BUSINESS_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Other');
INSERT INTO BUSINESS_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Personal');
INSERT INTO BUSINESS_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Professional');
INSERT INTO BUSINESS_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Service');

CREATE TABLE DIVISION
(
    DIVISION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER,
    BUSINESS_ID NUMBER NOT NULL,
    DIVISION_NAME VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (DIVISION_ID)
);

ALTER TABLE DIVISION ADD CONSTRAINT division_business_id_fk 
            FOREIGN KEY (BUSINESS_ID)
            REFERENCES PERSON(BUSINESS_ID);

CREATE TABLE DEPARTMENT
(
    DEPARTMENT_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DIVISION_ID NUMBER NOT NULL,
    DEPARTMENT_NAME VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (DEPARTMENT_ID)
);

ALTER TABLE DEPARTMENT ADD CONSTRAINT department_division_id_fk 
            FOREIGN KEY (DIVISION_ID)
            REFERENCES PERSON(DIVISION_ID);

CREATE TABLE DEPARTMENT_TELEPHONE
(
    DEPARTMENT_TELEPHONE_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DEPARTMENT_ID NUMBER NOT NULL,
    TELEPHONE_DESCRIPTION_ID NUMBER,
    DEPARTMENT_TELEPHONE VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (DEPARTMENT_TELEPHONE_ID)
);

--ALTER TABLE ...

CREATE TABLE DEPARTMENT_TELEPHONE_DESCRIPTION
(
    DEPARTMENT_TELEPHONE_DESCRIPTION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (DEPARTMENT_TELEPHONE_DESCRIPTION_ID)
);

INSERT INTO DEPARTMENT_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Cell');
INSERT INTO DEPARTMENT_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Fax');
INSERT INTO DEPARTMENT_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Home');
INSERT INTO DEPARTMENT_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Office');
INSERT INTO DEPARTMENT_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Other');


--i.e. hr_request_services@megacorp.com
CREATE TABLE DEPARTMENT_EMAIL_ADDRESS
(
    DEPARTMENT_EMAIL_ADDRESS_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DEPARTMENT_ID NUMBER NOT NULL,
    EMAIL_ADDRESS_DESCRIPTION_ID NUMBER,
    DEPARTMENT_EMAIL_ADDRESS VARCHAR2(50) CONSTRAINT  NOT NULL,
    PRIMARY KEY (DEPARTMENT_EMAIL_ADDRESS_ID)
);

CREATE TABLE DEPARTMENT_WEBSITE_ADDRESS
(
    DEPARTMENT_WEBSITE_ADDRESS_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DEPARTMENT_ID NUMBER NOT NULL,
    EMAIL_WEBSITE_DESCRIPTION_ID NUMBER,
    DEPARTMENT_WEBSITE_ADDRESS VARCHAR2(255) CONSTRAINT  NOT NULL,
    PRIMARY KEY (DEPARTMENT_WEBSITE_ADDRESS_ID)
);

CREATE TABLE BUSINESS_GROUP
(
    BUSINESS_GROUP_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DEPARTMENT_ID NUMBER NOT NULL,
    BUSINESS_GROUP_NAME VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (BUSINESS_GROUP_ID)
);

ALTER TABLE BUSINESS_GROUP ADD CONSTRAINT business_group_department_id_fk 
            FOREIGN KEY (DEPARTMENT_ID)
            REFERENCES PERSON(DEPARTMENT_ID);



CREATE TABLE EMAIL_ADDRESS_DESCRIPTION
(
    EMAIL_ADDRESS_DESCRIPTION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (EMAIL_ADDRESS_DESCRIPTION_ID)
);

INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Cell');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Corporate');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Departmental');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Office');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Business');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Other');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Personal');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Professional');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Service');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Union');


CREATE TABLE UNION_WEBSITE_ADDRESS
(
    UNION_WEBSITE_ADDRESS_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    UNION_ID NUMBER NOT NULL,
    UNION_WEBSITE_ADDRESS_DESCRIPTION_ID NUMBER,
    UNION_WEBSITE_ADDRESS VARCHAR2(100) CONSTRAINT  NOT NULL,
    PRIMARY KEY (UNION_WEBSITE_ADDRESS_ID)
);

CREATE TABLE UNION_WEBSITE_ADDRESS_DESCRIPTION
(
    UNION_WEBSITE_ADDRESS_DESCRIPTION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (UNION_WEBSITE_ADDRESS_DESCRIPTION_ID)
);

INSERT INTO UNION_WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Corporate');
INSERT INTO UNION_WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Business');
INSERT INTO UNION_WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Departmental');
INSERT INTO UNION_WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Other');
INSERT INTO UNION_WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Personal');
INSERT INTO UNION_WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Professional');
INSERT INTO UNION_WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Service');
INSERT INTO UNION_WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Union');
INSERT INTO UNION_WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Union_Local');








CREATE TABLE WEBSITE
(
    WEBSITE_ID NUMBER		CONSTRAINT  NOT NULL,
    PERSON_ID NUMBER		NOT NULL,
    LABEL VARCHAR2(20),
    WEB_ADDRESS VARCHAR2(200)	NOT NULL,
    PRIMARY KEY (WEBSITE_ID)
);



CREATE TABLE EMAIL_ADDRESS_DESCRIPTION
(
    EMAIL_ADDRESS_DESCRIPTION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (EMAIL_ADDRESS_DESCRIPTION_ID)
);

INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Cell');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Office');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Other');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Personal');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Professional');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Union');


--=======================================================
--new
--=======================================================


CREATE TABLE ORGANIZATION
(
    ORGANIZATION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER,
    ORGANIZATION_NAME VARCHAR2(25) NOT NULL,
    PRIMARY KEY (ORGANIZATION_ID)
);


CREATE TABLE ORGANIZATION_DESCRIPTION
(
    ORGANIZATION_DESCRIPTION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (ORGANIZATION_DESCRIPTION_ID)
);



CREATE TABLE UNION_TABLE
(
    UNION_ID NUMBER CONSTRAINT union_id_nn NOT NULL,
    VERSION NUMBER,
    UNION_NAME VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (UNION_ID)
);

CREATE SEQUENCE union_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE UNION_ADDRESS
(
    UNION_ADDRESS_ID NUMBER	CONSTRAINT  NOT NULL,
    UNION_ID NUMBER	NOT NULL,
    UNION_ADDRESS_DESCRIPTION_ID NUMBER,
    ADDRESS_LINE_1 VARCHAR2(50)	NOT NULL,
    ADDRESS_LINE_2 VARCHAR2(50),
    ADDRESS_LINE_3 VARCHAR2(50),
    ADDRESS_LINE_4 VARCHAR2(50),
    CITY VARCHAR2(50)	NOT NULL,
    STATE VARCHAR2(50)	NOT NULL,
    POSTAL_CODE VARCHAR2(15)		NOT NULL,
    COUNTRY VARCHAR2(50)			NOT NULL,
    PRIMARY KEY (UNION_ADDRESS_ID)
);

ALTER TABLE UNION_ADDRESS ADD CONSTRAINT union_address_union_id_fk 
            FOREIGN KEY (UNION_ID)
            REFERENCES PERSON(UNION_ID);

CREATE TABLE UNION_ADDRESS_DESCRIPTION
(
    UNION_ADDRESS_DESCRIPTION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(20)  NOT NULL UNIQUE,
    PRIMARY KEY (UNION_ADDRESS_DESCRIPTION_ID)
);

ALTER TABLE UNION_ADDRESS ADD CONSTRAINT union_address_union_id_fk 
            FOREIGN KEY (UNION_ID)
            REFERENCES PERSON(UNION_ID);



CREATE TABLE UNION_TELEPHONE
(
    UNION_TELEPHONE_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    UNION_ID NUMBER NOT NULL,
    UNION_TELEPHONE_DESCRIPTION_ID NUMBER,
    UNION_TELEPHONE VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (BUSINESS_TELEPHONE_ID)
);

CREATE TABLE UNION_TELEPHONE_DESCRIPTION
(
    UNION_TELEPHONE_DESCRIPTION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (UNION_TELEPHONE_DESCRIPTION_ID)
);

INSERT INTO UNION_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Cell');
INSERT INTO UNION_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Fax');
INSERT INTO UNION_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Home');
INSERT INTO UNION_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Office');
INSERT INTO UNION_TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Other');


CREATE TABLE UNION_EMAIL_ADDRESS
(
    UNION_EMAIL_ADDRESS_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    UNION_ID NUMBER NOT NULL,
    EMAIL_ADDRESS_DESCRIPTION_ID NUMBER,
    UNION_EMAIL_ADDRESS VARCHAR2(50) CONSTRAINT  NOT NULL,
    PRIMARY KEY (BUSINESS_EMAIL_ADDRESS_ID)
);

CREATE TABLE UNION_EMAIL_ADDRESS_DESCRIPTION
(
    UNION_EMAIL_ADDRESS_DESCRIPTION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (UNION_EMAIL_ADDRESS_DESCRIPTION_ID)
);

INSERT INTO UNION_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Cell');
INSERT INTO UNION_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Corporate');
INSERT INTO UNION_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Departmental');
INSERT INTO UNION_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Office');
INSERT INTO UNION_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Business');
INSERT INTO UNION_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Other');
INSERT INTO UNION_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Personal');
INSERT INTO UNION_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Professional');
INSERT INTO UNION_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Service');
INSERT INTO UNION_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Union');
INSERT INTO UNION_EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Union_Local');


CREATE TABLE UNION_WEBSITE_ADDRESS
(
    UNION_WEBSITE_ADDRESS_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    UNION_ID NUMBER NOT NULL,
    UNION_WEBSITE_ADDRESS_DESCRIPTION_ID NUMBER,
    UNION_WEBSITE_ADDRESS VARCHAR2(100) CONSTRAINT  NOT NULL,
    PRIMARY KEY (UNION_WEBSITE_ADDRESS_ID)
);

CREATE TABLE UNION_WEBSITE_ADDRESS_DESCRIPTION
(
    UNION_WEBSITE_ADDRESS_DESCRIPTION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (UNION_WEBSITE_ADDRESS_DESCRIPTION_ID)
);

INSERT INTO UNION_WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Corporate');
INSERT INTO UNION_WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Business');
INSERT INTO UNION_WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Departmental');
INSERT INTO UNION_WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Other');
INSERT INTO UNION_WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Personal');
INSERT INTO UNION_WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Professional');
INSERT INTO UNION_WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Service');
INSERT INTO UNION_WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Union');
INSERT INTO UNION_WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Union_Local');



CREATE TABLE UNION_LOCAL
(
    UNION_LOCAL_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER,
    UNION_LOCAL_ID NUMBER NOT NULL,
    UNION_LOCAL_NAME VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (UNION_LOCAL_ID)
);

CREATE SEQUENCE union_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE UNION_LOCAL_ADDRESS
(
    UNION_LOCAL_ADDRESS_ID NUMBER	CONSTRAINT  NOT NULL,
    UNION_LOCAL_ID NUMBER	NOT NULL,
    UNION_LOCAL_ADDRESS_DESCRIPTION_ID NUMBER,
    ADDRESS_LINE_1 VARCHAR2(50)	NOT NULL,
    ADDRESS_LINE_2 VARCHAR2(50),
    ADDRESS_LINE_3 VARCHAR2(50),
    ADDRESS_LINE_4 VARCHAR2(50),
    CITY VARCHAR2(50)	NOT NULL,
    STATE VARCHAR2(50)	NOT NULL,
    POSTAL_CODE VARCHAR2(15)		NOT NULL,
    COUNTRY VARCHAR2(50)			NOT NULL,
    PRIMARY KEY (UNION_LOCAL_ADDRESS_ID)
);

ALTER TABLE UNION_LOCAL_ADDRESS ADD CONSTRAINT union_address_union_id_fk 
            FOREIGN KEY (UNION_LOCAL_ID)
            REFERENCES PERSON(UNION_LOCAL_ID);

CREATE TABLE UNION_LOCAL_ADDRESS_DESCRIPTION
(
    UNION_LOCAL_ADDRESS_DESCRIPTION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(20)  NOT NULL UNIQUE,
    PRIMARY KEY (UNION_LOCAL_ADDRESS_DESCRIPTION_ID)
);

ALTER TABLE UNION_LOCAL_ADDRESS ADD CONSTRAINT union_address_union_id_fk 
            FOREIGN KEY (UNION_LOCAL_ID)
            REFERENCES PERSON(UNION_LOCAL_ID);

INSERT INTO UNION_LOCAL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Headquarters');
INSERT INTO UNION_LOCAL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Local');


CREATE TABLE UNION_LOCAL_TELEPHONE
(
    UNION_LOCAL_TELEPHONE_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    UNION_LOCAL_ID NUMBER NOT NULL,
    UNION_LOCAL_TELEPHONE_DESCRIPTION_ID NUMBER,
    UNION_LOCAL_TELEPHONE VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (BUSINESS_TELEPHONE_ID)
);


CREATE TABLE UNION_LOCAL_EMAIL_ADDRESS
(
    UNION_LOCAL_EMAIL_ADDRESS_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    UNION_LOCAL_ID NUMBER NOT NULL,
    EMAIL_ADDRESS_DESCRIPTION_ID NUMBER,
    UNION_LOCAL_EMAIL_ADDRESS VARCHAR2(50) CONSTRAINT  NOT NULL,
    PRIMARY KEY (BUSINESS_EMAIL_ADDRESS_ID)
);


CREATE TABLE UNION_LOCAL_WEBSITE_ADDRESS
(
    UNION_LOCAL_WEBSITE_ADDRESS_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    UNION_LOCAL_ID NUMBER NOT NULL,
    WEBSITE_ADDRESS_DESCRIPTION_ID NUMBER,
    UNION_LOCAL_WEBSITE_ADDRESS VARCHAR2(100) CONSTRAINT NOT NULL,
    PRIMARY KEY (UNION_LOCAL_WEBSITE_ADDRESS_ID)
);


CREATE TABLE ADDRESS_DESCRIPTION
(
    ADDRESS_DESCRIPTION_ID NUMBER CONSTRAINT NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(25)  NOT NULL UNIQUE,
    PRIMARY KEY (ADDRESS_DESCRIPTION_ID)
);

INSERT INTO ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Division');
INSERT INTO ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Field Office');
INSERT INTO ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Headquarters');
INSERT INTO ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Local');
INSERT INTO ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Subsidiary');

CREATE TABLE TELEPHONE_DESCRIPTION
(
    TELEPHONE_DESCRIPTION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (TELEPHONE_DESCRIPTION_ID)
);

INSERT INTO TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Cell');
INSERT INTO TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Fax');
INSERT INTO TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Home');
INSERT INTO TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Office');
INSERT INTO TELEPHONE_DESCRIPTION (DESCRIPTION) VALUES ('Other');

CREATE TABLE EMAIL_ADDRESS_DESCRIPTION
(
    EMAIL_ADDRESS_DESCRIPTION_ID NUMBER CONSTRAINT NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(25) CONSTRAINT NOT NULL,
    PRIMARY KEY (EMAIL_ADDRESS_DESCRIPTION_ID)
);

INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Cell');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Corporate');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Departmental');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Office');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Business');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Other');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Personal');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Professional');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Service');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Union');
INSERT INTO EMAIL_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Union Local');


CREATE TABLE WEBSITE_ADDRESS_DESCRIPTION
(
    WEBSITE_ADDRESS_DESCRIPTION_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER, 
    DESCRIPTION VARCHAR2(25) CONSTRAINT  NOT NULL,
    PRIMARY KEY (WEBSITE_ADDRESS_DESCRIPTION_ID)
);

INSERT INTO WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Corporate');
INSERT INTO WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Business');
INSERT INTO WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Departmental');
INSERT INTO WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Other');
INSERT INTO WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Personal');
INSERT INTO WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Professional');
INSERT INTO WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Service');
INSERT INTO WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Union');
INSERT INTO WEBSITE_ADDRESS_DESCRIPTION (DESCRIPTION) VALUES ('Union Local');






--///////////////////////////////////////////////




CREATE SEQUENCE customers_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;



CREATE TABLE MANAGER
(
    MANAGER_ID NUMBER CONSTRAINT manager_id_nn NOT NULL,
    VERSION NUMBER, 
    FULL_PART_STATUS CHAR(2) DEFAULT 'FT' CONSTRAINT FULL_PART_nn NOT NULL,
    TEMPORARY_STATUS CHAR(1) DEFAULT 0 CONSTRAINT TEMPORARY_nn NOT NULL,
    HIGHLY_COMPENSATED CHAR(1) DEFAULT 0 CONSTRAINT HIGHLY_nn NOT NULL,
    PRIMARY KEY (MANAGER_ID)
);

CREATE TABLE MANAGER
(
    MANAGER_ID NUMBER CONSTRAINT manager_id_nn NOT NULL,
    VERSION NUMBER, 
    FULL_PART_STATUS VARCHAR2(2) DEFAULT 'FT',
    TEMPORARY_STATUS CHAR(1) DEFAULT 0,
    HIGHLY_COMPENSATED CHAR(1) DEFAULT 0,
    PRIMARY KEY (MANAGER_ID)
);

CREATE TABLE MANAGER
(
    MANAGER_ID NUMBER CONSTRAINT NOT NULL,
    VERSION NUMBER, 
    FULL_PART_STATUS VARCHAR2(2) DEFAULT 'FT',
    TEMPORARY_STATUS CHAR(1) DEFAULT 0,
    HIGHLY_COMPENSATED CHAR(1) DEFAULT 0,
    PRIMARY KEY (MANAGER_ID)
);









CREATE TABLE APPLICANT
(
    APPLICANT_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER,
    APPLICATION_DATE DATE,
    PRIMARY KEY (APPLICANT_ID)
);

CREATE TABLE CUSTOMER
(
    CUSTOMER_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER,
    DATE_OF_PURCHASE DATE,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE FORMER_CUSTOMER
(
    FORMER_CUSTOMER_ID NUMBER CONSTRAINT  NOT NULL,
    VERSION NUMBER,
    EFFECTIVE_DATE DATE,
    PRIMARY KEY (FORMER_CUSTOMER_ID)
);




============================================================

CREATE TABLE PERSON
(
    PERSON_ID NUMBER
        CONSTRAINT person_id_nn NOT NULL,
    ORGANIZATION_NAME VARCHAR2(50),
    TITLE VARCHAR2(30),
    LABEL VARCHAR2(20),
    LASTNAME VARCHAR2(25)
        CONSTRAINT lastname_nn NOT NULL,
    FIRSTNAME VARCHAR2(25),
    MIDDLENAME VARCHAR2(25),
    BIRTHDAY DATE
);

REM --insert "blank" person where "deleted" addresses are moved
INSERT INTO PERSON VALUES 
(0, ' ', ' ', 'Other', ' ', ' ', ' ', DATE '1940-01-01');

CREATE SEQUENCE person_seq
START WITH 1 INCREMENT BY 1
NOCACHE NOCYCLE;

ALTER TABLE PERSON ADD 
(
    CONSTRAINT person_id_pk 
    PRIMARY KEY (PERSON_ID)
);


CREATE TABLE ADDRESS
(
    ADDRESS_ID NUMBER
        CONSTRAINT address_id_nn NOT NULL,
    PERSON_ID NUMBER,
    LABEL VARCHAR2(20),
    ADDRESS_LINE_1 VARCHAR2(50)
        CONSTRAINT address_line_1_nn NOT NULL,
    ADDRESS_LINE_2 VARCHAR2(50),
    ADDRESS_LINE_3 VARCHAR2(50),
    ADDRESS_LINE_4 VARCHAR2(50),
    CITY VARCHAR2(50)
        CONSTRAINT city_nn NOT NULL,
    STATE VARCHAR2(50)
        CONSTRAINT state_nn NOT NULL,
    POSTAL_CODE VARCHAR2(50)
        CONSTRAINT postal_code_nn NOT NULL,
    COUNTRY VARCHAR2(50)
        CONSTRAINT country_nn NOT NULL
);

CREATE SEQUENCE address_seq
START WITH 1 INCREMENT BY 1
NOCACHE NOCYCLE;

ALTER TABLE ADDRESS ADD
(
    CONSTRAINT address_id_pk
        PRIMARY KEY (ADDRESS_ID),
    CONSTRAINT address_person_id_fk
        FOREIGN KEY (PERSON_ID)
        REFERENCES PERSON(PERSON_ID)
);









